import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
const [repo, file, n = "14"] = process.argv.slice(2);
const dir = mkdtempSync(join(tmpdir(), "s-"));
const git = (cwd, a) => execFileSync("git", a, { cwd, encoding: "utf8", maxBuffer: 1 << 28 });
git(dir, ["clone", "--depth", "1", "--filter=blob:none", "--no-checkout", "--quiet", `https://github.com/${repo}.git`, "r"]);
const w = join(dir, "r");
git(w, ["sparse-checkout", "set", "--no-cone", file]);
git(w, ["checkout", "--quiet", "HEAD"]);
console.log(readFileSync(join(w, file), "utf8").split("\n").slice(0, Number(n)).join("\n"));
rmSync(dir, { recursive: true, force: true });
