// @vitest-environment jsdom
import { act } from "react";
import userEvent from "@testing-library/user-event";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
let SearchTrigger: typeof import("@/components/search/search-trigger").SearchTrigger;
import type { NavProject } from "@/lib/shell/nav";
import type { KeyHit } from "@/lib/search/key-href";
import { find, input, key, render } from "./helpers/dom";

vi.setConfig({ testTimeout: 20_000 });
const mocks = vi.hoisted(() => ({ keys: vi.fn(), memberships: vi.fn(), fetch: vi.fn(), pathname: "/docs/start" }));
vi.mock("@/app/search/actions", () => ({ searchKeysAction: mocks.keys, loadSearchMembershipsAction: mocks.memberships }));
vi.mock("next/navigation", () => ({ usePathname: () => mocks.pathname }));
const account = { name: "Tester", email: null, image: null };
const demo: NavProject = { slug: "demo", name: "Demo", role: "OWNER", archived: false, image: null, defaultSurfaceSlug: "web" };
const docs = [{ id: "doc:start", title: "Start", href: "/docs/start", body: "Learn settings demo and publishing" }, { id: "doc:publish", title: "Publishing", href: "/docs/start#publish", body: "Publish translations", anchor: "publish" }];
const hit = (id: string, patch: Partial<KeyHit> = {}): KeyHit => ({ id, key: id, namespace: "_root", sourceText: "Source", surfaceSlug: "web", slug: "demo", name: "Demo", inKey: true, localeCode: null, value: null, ...patch });
function deferred<T>() { let resolve!: (value: T) => void; const promise = new Promise<T>(r => { resolve = r; }); return { promise, resolve: async (value: T) => { await act(async () => resolve(value)); } }; }
const dialog = () => document.querySelector('[role="dialog"]');
const query = () => find<HTMLInputElement>(document.body, '[role="combobox"]');
const opener = () => find<HTMLButtonElement>(document.body, 'button[aria-label="Search"]');
const options = () => [...document.querySelectorAll<HTMLElement>('[role="option"]')];
const group = (label: string) => [...document.querySelectorAll<HTMLElement>('[role="group"]')].find(el => el.firstElementChild?.textContent === label);
async function open() { await act(async () => { await userEvent.setup().click(opener()); }); }
async function close() { await key(query(), "Escape"); await vi.waitFor(() => expect(dialog()).toBeNull()); }
async function tick(ms = 250) { await act(async () => { await vi.advanceTimersByTimeAsync(ms); }); }
beforeEach(async () => { vi.resetModules(); SearchTrigger = (await import("@/components/search/search-trigger")).SearchTrigger; mocks.keys.mockReset().mockResolvedValue({ ok: true, hits: [] }); mocks.memberships.mockReset().mockResolvedValue({ ok: true, memberships: [demo] }); mocks.fetch.mockReset().mockResolvedValue({ ok: true, json: async () => ({ docs }) }); vi.stubGlobal("fetch", mocks.fetch); mocks.pathname = "/docs/start"; window.history.replaceState(null, "", "/docs/start"); Object.defineProperty(navigator, "platform", { configurable: true, value: "MacIntel" }); });
afterEach(() => { vi.useRealTimers(); vi.unstubAllGlobals(); vi.restoreAllMocks(); });

it("capsule labels, initial input focus, preview and public anonymous boundaries", async () => {
  await render(<SearchTrigger account={null} />); expect(opener().getAttribute("aria-haspopup")).toBe("dialog"); expect(opener().getAttribute("aria-keyshortcuts")).toBe("Meta+K"); expect(opener().textContent).toContain("Search…"); await open(); expect(document.activeElement).toBe(query()); expect(query().hasAttribute("data-initial-focus")).toBe(true); expect(group("Projects")).toBeUndefined(); expect(group("Keys")).toBeUndefined(); expect(group("Menus")?.textContent).toContain("Changelog"); expect(group("Docs")?.textContent).toContain("Browse all docs"); expect(mocks.memberships).not.toHaveBeenCalled(); await close(); await vi.waitFor(() => expect(document.activeElement).toBe(opener()));
});
it("app membership preview reuses supplied rows without loading memberships", async () => {
  mocks.pathname = "/projects/demo"; await render(<SearchTrigger account={account} memberships={[demo, { ...demo, slug: "old", name: "Old", archived: true }]} />); await open(); expect(group("Projects")?.textContent).toContain("View all projects"); expect(group("Projects")?.textContent).toContain("Archived"); expect(group("Projects")?.querySelector("svg")).not.toBeNull(); expect(group("Menus")?.textContent).toContain("Settings"); expect(mocks.memberships).not.toHaveBeenCalled(); expect(group("Keys")).toBeUndefined();
});
it("signed-in zero projects preview keeps work menus and docs", async () => { await render(<SearchTrigger account={account} memberships={[]} />); await open(); expect(group("Projects")).toBeUndefined(); expect(group("Menus")?.textContent).toContain("MCP connector"); expect(group("Docs")?.textContent).toContain("Browse all docs"); });
it("public membership refresh per opening replaces creation, archive and role changes", async () => {
  const view = await render(<SearchTrigger account={account} />); expect(mocks.memberships).not.toHaveBeenCalled(); await open(); expect(mocks.memberships).toHaveBeenCalledTimes(1); await input(query(), "demo"); await view.rerender(<SearchTrigger account={account} />); expect(mocks.memberships).toHaveBeenCalledTimes(1); await close(); const fresh = deferred<{ ok: true; memberships: NavProject[] }>(); mocks.memberships.mockReturnValueOnce(fresh.promise); await open(); expect(mocks.memberships).toHaveBeenCalledTimes(2); expect(group("Projects")).toBeUndefined(); expect(document.body.textContent).toContain("Loading projects…"); await fresh.resolve({ ok: true, memberships: [{ ...demo, archived: true, role: "EDITOR" }, { ...demo, slug: "new", name: "Created" }] }); expect(group("Projects")?.textContent).toContain("Created"); expect(group("Projects")?.textContent).toContain("Archived"); await input(query(), "settings demo"); expect(group("Menus")).toBeUndefined(); await close(); mocks.pathname = "/privacy"; await view.rerender(<SearchTrigger account={account} />); await open(); expect(mocks.memberships).toHaveBeenCalledTimes(3);
});
it("closed and reopened membership generations ignore the old response", async () => { const old = deferred<{ ok: true; memberships: NavProject[] }>(); const fresh = deferred<{ ok: true; memberships: NavProject[] }>(); mocks.memberships.mockReturnValueOnce(old.promise).mockReturnValueOnce(fresh.promise); await render(<SearchTrigger account={account} />); await open(); await close(); await open(); await fresh.resolve({ ok: true, memberships: [{ ...demo, name: "Fresh" }] }); await old.resolve({ ok: true, memberships: [{ ...demo, name: "Stale" }] }); expect(group("Projects")?.textContent).toContain("Fresh"); expect(document.body.textContent).not.toContain("Stale"); });
it("membership failure falls back to anonymous menus and skips key search", async () => { mocks.memberships.mockResolvedValue({ ok: false, error: "unauthorized" }); await render(<SearchTrigger account={account} />); await open(); vi.useFakeTimers({ shouldAdvanceTime: true }); await input(query(), "demo"); await tick(); expect(group("Projects")).toBeUndefined(); expect(mocks.keys).not.toHaveBeenCalled(); });
it("menus use token AND immediately, keys send the whole trimmed bounded query at 250ms", async () => { await render(<SearchTrigger account={account} memberships={[demo]} />); await open(); vi.useFakeTimers({ shouldAdvanceTime: true }); await input(query(), "settings demo"); expect(group("Menus")?.textContent).toContain("Settings"); expect(group("Menus")?.querySelectorAll("mark").length).toBe(2); await tick(249); expect(mocks.keys).not.toHaveBeenCalled(); await tick(1); expect(mocks.keys).toHaveBeenCalledWith("settings demo", null); await input(query(), "  a "); await tick(); expect(mocks.keys).toHaveBeenCalledTimes(1); await input(query(), "x".repeat(201)); await tick(); expect(mocks.keys).toHaveBeenLastCalledWith("x".repeat(200), null); });
it("ABA key request race and old pending debounce cannot overwrite current results", async () => { const a = deferred<{ ok: true; hits: KeyHit[] }>(); const b = deferred<{ ok: true; hits: KeyHit[] }>(); const fresh = deferred<{ ok: true; hits: KeyHit[] }>(); mocks.keys.mockReturnValueOnce(a.promise).mockReturnValueOnce(b.promise).mockReturnValueOnce(fresh.promise); await render(<SearchTrigger account={account} memberships={[demo]} />); await open(); vi.useFakeTimers({ shouldAdvanceTime: true }); await input(query(), "alpha"); await tick(); await input(query(), "beta"); await tick(); await input(query(), "alpha"); await tick(); await fresh.resolve({ ok: true, hits: [hit("Fresh-alpha")] }); await a.resolve({ ok: true, hits: [hit("Old-alpha")] }); await b.resolve({ ok: true, hits: [hit("Old-beta")] }); expect(group("Keys")?.textContent).toContain("Fresh-alpha"); expect(document.body.textContent).not.toContain("Old-"); });
it("key failure leaves local groups, status outside listbox and no pending empty state", async () => { const response = deferred<{ ok: false; error: "unavailable" }>(); mocks.keys.mockReturnValueOnce(response.promise); await render(<SearchTrigger account={account} memberships={[demo]} />); await open(); vi.useFakeTimers({ shouldAdvanceTime: true }); await input(query(), "demo"); expect(document.body.textContent).toContain("Loading keys…"); expect(document.body.textContent).not.toContain("No results"); await tick(); await response.resolve({ ok: false, error: "unavailable" }); expect(group("Projects")?.textContent).toContain("Demo"); expect(document.body.textContent).toContain("Keys can't be searched right now."); expect(find(document.body, '[role="listbox"]').querySelector('[role="status"]')).toBeNull(); });
it("docs failure can retry next opening and zero settled hits has no exit button", async () => { mocks.fetch.mockRejectedValueOnce(new Error("offline")); await render(<SearchTrigger account={null} />); await open(); expect(document.body.textContent).toContain("Docs can't be searched right now."); await input(query(), "unmatched"); expect(document.body.textContent).toContain('No results for “unmatched”'); expect(dialog()?.querySelector("button")).toBeNull(); await close(); await open(); expect(mocks.fetch).toHaveBeenCalledTimes(2); });
it("pending docs show status without NoMatch while local results are immediately usable", async () => { const response = deferred<{ ok: true; json: () => Promise<{ docs: typeof docs }> }>(); mocks.fetch.mockReturnValueOnce(response.promise); await render(<SearchTrigger account={account} memberships={[demo]} />); await open(); expect(group("Projects")?.textContent).toContain("Demo"); expect(document.body.textContent).toContain("Loading docs…"); await input(query(), "absent"); expect(document.body.textContent).not.toContain("No results"); await response.resolve({ ok: true, json: async () => ({ docs }) }); });
it.each(["double  space", "tab\tspace", "line\nbreak"])("original whole-string %j remains highlighted and description has normal collapsing nowrap CSS", async literal => { mocks.keys.mockResolvedValue({ ok: true, hits: [hit("key", { inKey: false, sourceText: "prefix ".repeat(50) + literal + " end", localeCode: "ko", value: "prefix ".repeat(50) + literal + " end" })] }); await render(<SearchTrigger account={account} memberships={[demo]} />); await open(); vi.useFakeTimers({ shouldAdvanceTime: true }); await input(query(), literal); await tick(); const result = group("Keys"); expect(result).toBeDefined(); const mark = find<HTMLElement>(result!, "mark"); expect(mark.textContent).toBe(literal); expect(mark.parentElement?.parentElement?.className).toContain("whitespace-nowrap"); expect(mark.parentElement?.parentElement?.className).not.toMatch(/whitespace-pre/); expect(result?.querySelector('[data-search-locale]')?.textContent).toBe("ko"); });
it("key-only hit shows source introduction; original and docs later matches get snippet marks", async () => { mocks.keys.mockResolvedValue({ ok: true, hits: [hit("Publish", { sourceText: "Introduction" }), hit("source", { inKey: false, sourceText: "prefix ".repeat(100) + "Publish" })] }); await render(<SearchTrigger account={account} memberships={[demo]} />); await open(); vi.useFakeTimers({ shouldAdvanceTime: true }); await input(query(), "publish"); await tick(); expect(group("Keys")?.textContent).toContain("Introduction"); expect(group("Keys")?.querySelectorAll("mark").length).toBe(2); expect(group("Docs")?.querySelector("mark")?.textContent?.toLowerCase()).toBe("publish"); });
it("late Keys insertion preserves active Docs ID and Enter clicks that real link", async () => { const response = deferred<{ ok: true; hits: KeyHit[] }>(); mocks.keys.mockReturnValueOnce(response.promise); await render(<SearchTrigger account={account} memberships={[demo]} />); await open(); vi.useFakeTimers({ shouldAdvanceTime: true }); await input(query(), "publishing"); const id = query().getAttribute("aria-activedescendant")!; const option = document.getElementById(id); expect(option).not.toBeNull(); const link = find<HTMLAnchorElement>(option!, "a"); const click = vi.spyOn(link, "click"); await tick(); await response.resolve({ ok: true, hits: [hit("publishing-key")] }); expect(query().getAttribute("aria-activedescendant")).toBe(id); await key(query(), "Enter"); expect(click).toHaveBeenCalledOnce(); expect(dialog()).toBeNull(); });
it("actual IME composition and native composing Escape/Enter keep dialog and input focus", async () => { await render(<SearchTrigger account={null} />); await open(); await act(async () => { query().dispatchEvent(new CompositionEvent("compositionstart", { bubbles: true })); }); await key(query(), "Escape"); await key(query(), "Enter"); expect(dialog()).not.toBeNull(); expect(document.activeElement).toBe(query()); await act(async () => { query().dispatchEvent(new CompositionEvent("compositionend", { bubbles: true })); }); await key(query(), "Escape", { isComposing: true }); expect(dialog()).not.toBeNull(); await key(query(), "Escape", { keyCode: 229 }); expect(dialog()).not.toBeNull(); await close(); });
it("same-doc hash selection lands heading after close without trigger focus restoration", async () => { await render(<><div data-public-scroller><h2 id="publish" tabIndex={-1}>Publish heading</h2></div><SearchTrigger account={null} /></>); const scroller = find<HTMLElement>(document.body, '[data-public-scroller]'); const scroll = vi.spyOn(scroller, "scrollTo"); await open(); await input(query(), "publish"); const link = find<HTMLAnchorElement>(group("Docs")!, 'a[href="/docs/start#publish"]'); await act(async () => link.click()); expect(dialog()).toBeNull(); await vi.waitFor(() => expect(document.activeElement).toBe(document.getElementById("publish"))); expect(scroll).toHaveBeenCalledWith({ top: -48, behavior: "smooth" }); expect(window.location.hash).toBe("#publish"); });
it("shortcuts respect platform, editing targets, existing dialog and menu", async () => { const view = await render(<SearchTrigger account={null} />); await key(document.body, "k", { ctrlKey: true }); expect(dialog()).toBeNull(); const area = document.createElement("textarea"); document.body.append(area); area.focus(); await key(area, "k", { metaKey: true }); expect(dialog()).toBeNull(); area.remove(); const menu = document.createElement("div"); menu.setAttribute("role", "menu"); document.body.append(menu); await key(document.body, "k", { metaKey: true }); expect(dialog()).toBeNull(); menu.remove(); await key(document.body, "k", { metaKey: true, isComposing: true }); expect(dialog()).toBeNull(); await key(document.body, "k", { metaKey: true }); expect(dialog()).not.toBeNull(); await key(query(), "k", { metaKey: true }); expect(dialog()).not.toBeNull(); await close(); Object.defineProperty(navigator, "platform", { configurable: true, value: "Win32" }); await view.rerender(<SearchTrigger account={null} />); await key(document.body, "k", { ctrlKey: true }); expect(dialog()).not.toBeNull(); });
